services:
  - type: web
    name: ticket-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    region: frankfurt
